services:
  nacos:
    image: nacos/nacos-server:v2.5.2
    container_name: nacos-prism
    restart: always
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=host.docker.internal
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=TmFuUHJvZHVjZWQxMjA5MTIwOU5hblByb2R1Y2VkMTIwOTEyMDlOYW5Qcm9kdWNlZDEyMDkxMjA5
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=Nan12091209
      - JVM_XMS=512m
      - JVM_XMX=512m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - C:/Users/nanpr/docker/nacos/conf:/home/nacos/conf
      - C:/Users/nanpr/docker/nacos/data:/home/nacos/data
      - C:/Users/nanpr/docker/nacos/logs:/home/nacos/logs
    networks:
      - prism-net

  postgres:
    image: postgres:16-alpine
    container_name: postgres-prism
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Nan12091209
      - POSTGRES_DB=prism
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/nanpr/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - prism-net

  redis:
    image: redis:7-alpine
    container_name: redis-prism
    restart: always
    command: ["redis-server","--appendonly","yes","--requirepass","Nan12091209"]
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/nanpr/docker/redis/data:/data
    networks:
      - prism-net

networks:
  prism-net:
    driver: bridge