package nan.produced.prism.payment.domain.model;

public enum PaymentEventType {
    ORDER_CREATED,
    ORDER_PAID,
    ORDER_FAILED,
    ORDER_CANCELED,
    ORDER_REFUNDED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED,
    SUBSCRIPTION_PAST_DUE,
    SUBSCRIPTION_SYNCED,
    WEBHOOK_RECEIVED,
    WEBHOOK_PROCESSED
}
