-- ---------------------------------------------------------------------------
-- Optimize dashboard query performance (SPA-facing list endpoints)
-- ---------------------------------------------------------------------------

-- Device command log list queries are always scoped by user_id and time range.
CREATE INDEX IF NOT EXISTS idx_pcc_device_command_log_user_time
    ON pcc_device_command_log(user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_pcc_device_command_log_user_device_time
    ON pcc_device_command_log(user_id, device_id, created_at DESC, id DESC);

-- Reduce index/storage pressure: operation_id is a UUID (generated by core-service).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_name = 'pcc_device_command_log'
           AND column_name = 'operation_id'
           AND data_type <> 'uuid'
    ) THEN
        IF EXISTS (
            SELECT 1
              FROM pcc_device_command_log
             WHERE operation_id IS NOT NULL
               AND operation_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            LIMIT 1
        ) THEN
            RAISE EXCEPTION 'pcc_device_command_log.operation_id contains non-UUID values; cannot convert to UUID safely';
        END IF;

        DROP INDEX IF EXISTS uk_pcc_device_command_log_operation_id;
        ALTER TABLE pcc_device_command_log
            ALTER COLUMN operation_id TYPE UUID USING operation_id::uuid;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_pcc_device_command_log_operation_id
            ON pcc_device_command_log(operation_id);
    END IF;
END $$;

